// Builds the offline icon bundle the web UI ships with.
//
// The UI used to load the Iconify web component from code.iconify.design and
// let it fetch each icon's path data from Iconify's public API at runtime.
// That is an unprompted third-party request from a product whose whole pitch
// is that nothing leaves your machine, and it left every icon blank on an
// isolated network. So: resolve every icon this repo can name, ahead of time,
// into a module the bundle carries.
//
// Scanning rather than an explicit list, because icon names are written in
// three places — markup (`icon="x:y"`), plain string constants the markup
// binds to (`const ICON = { ok: 'lucide:check' }`), curated expert profiles,
// and one Go handler — and a hand-maintained list would rot the first time
// someone adds an icon. Candidates are validated against the real collections,
// so a false positive from the regex (any "word:word" string) simply finds no
// icon and is dropped.
//
// Run by `npm run build` (prebuild) and by the test that asserts the committed
// bundle still covers every icon in the tree.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, dirname, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getIcons } from '@iconify/utils'

const webDir = dirname(dirname(fileURLToPath(import.meta.url)))
const repoRoot = dirname(webDir)

// Where an icon name can legitimately appear. Keep in sync with the comment
// above; anything outside these roots is not searched and would render blank.
const ROOTS = [
  { dir: join(webDir, 'src'), exts: ['.svelte', '.ts', '.js', '.html'] },
  { dir: join(repoRoot, 'internal/agentprofile/defaults'), exts: ['.md'] },
  { dir: join(repoRoot, 'internal/server'), exts: ['.go'] },
]

// A quoted iconify name: prefix:name, both lowercase kebab. Deliberately loose
// — validation against the collections is what rejects the false positives.
const CANDIDATE = /['"]([a-z0-9]+(?:-[a-z0-9]+)*:[a-z0-9]+(?:-[a-z0-9]+)*)['"]/g

function walk(dir, exts, out = []) {
  let entries
  try {
    entries = readdirSync(dir)
  } catch {
    return out // an optional root that doesn't exist in this checkout
  }
  for (const entry of entries) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      if (entry === 'node_modules' || entry === 'dist') continue
      walk(full, exts, out)
    } else if (exts.some((e) => entry.endsWith(e))) {
      out.push(full)
    }
  }
  return out
}

export function collectCandidates() {
  const byPrefix = new Map()
  for (const { dir, exts } of ROOTS) {
    for (const file of walk(dir, exts)) {
      const text = readFileSync(file, 'utf8')
      for (const [, name] of text.matchAll(CANDIDATE)) {
        const [prefix, icon] = name.split(':')
        if (!byPrefix.has(prefix)) byPrefix.set(prefix, new Set())
        byPrefix.get(prefix).add(icon)
      }
    }
  }
  return byPrefix
}

function loadCollection(prefix) {
  try {
    const path = join(webDir, 'node_modules/@iconify-json', prefix, 'icons.json')
    return JSON.parse(readFileSync(path, 'utf8'))
  } catch {
    return null // not an icon set we depend on — every candidate under it is a false positive
  }
}

export function buildBundle() {
  const resolved = []
  const missing = []
  for (const [prefix, names] of [...collectCandidates()].sort()) {
    const collection = loadCollection(prefix)
    if (!collection) continue
    const wanted = [...names].sort()
    const subset = getIcons(collection, wanted)
    if (!subset || !Object.keys(subset.icons).length) continue
    resolved.push(subset)
    for (const name of wanted) {
      // getIcons resolves aliases into `icons`, so check both maps.
      if (!subset.icons[name] && !(subset.aliases ?? {})[name]) missing.push(`${prefix}:${name}`)
    }
  }
  return { resolved, missing }
}

function main() {
  const { resolved, missing } = buildBundle()
  const count = resolved.reduce((n, c) => n + Object.keys(c.icons).length, 0)

  const out = join(webDir, 'src/lib/icons.generated.ts')
  writeFileSync(
    out,
    `// Code generated by scripts/gen-icons.mjs. DO NOT EDIT.
//
// Every icon this repo names, resolved offline so the UI never calls the
// Iconify API. Regenerate with \`npm run gen:icons\` after adding an icon;
// icons.test.ts fails if this file has fallen behind the source tree.
import type { IconifyJSON } from 'iconify-icon'

export const iconCollections: IconifyJSON[] = ${JSON.stringify(resolved)}
`,
    'utf8',
  )

  const bytes = statSync(out).size
  console.log(`icons: ${count} icons from ${resolved.length} collections → ${relative(repoRoot, out)} (${(bytes / 1024).toFixed(0)} KB)`)
  if (missing.length) {
    // Not fatal: a name can look like an icon and not be one. Worth printing
    // so a genuine typo in a real icon name is visible.
    console.log(`icons: ${missing.length} unresolved candidate(s): ${missing.slice(0, 10).join(', ')}${missing.length > 10 ? ' …' : ''}`)
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main()
